import wx
class EmailClient(wx.Frame):
    def __init__(self, parent, title):
        super(EmailClient, self).__init__(parent, title=title, size=(600, 400))
        panel = wx.Panel(self)
        my_sizer = wx.BoxSizer(wx.VERTICAL)
        # 登录区域
        login_sizer = wx.BoxSizer(wx.HORIZONTAL)
        email_label = wx.StaticText(panel, label="邮箱:")
        login_sizer.Add(email_label, 0, wx.ALL | wx.LEFT, 10)
        email_text = wx.TextCtrl(panel)
        login_sizer.Add(email_text, 0, wx.ALL | wx.EXPAND, 10)
        password_label = wx.StaticText(panel, label="密码:")
        login_sizer.Add(password_label, 0, wx.ALL | wx.LEFT, 10)
        password_text = wx.TextCtrl(panel, style=wx.TE_PASSWORD)
        login_sizer.Add(password_text, 0, wx.ALL | wx.EXPAND, 10)
        login_button = wx.Button(panel, label="登录")
        login_sizer.Add(login_button, 0, wx.ALL | wx.CENTER, 5)
        my_sizer.Add(login_sizer, 0, wx.ALL | wx.EXPAND, 10)
        # 发送邮件区域
        send_sizer = wx.BoxSizer(wx.HORIZONTAL)
        to_label = wx.StaticText(panel, label="收件人:")
        send_sizer.Add(to_label, 0, wx.ALL | wx.LEFT, 10)
        to_text = wx.TextCtrl(panel)
        send_sizer.Add(to_text, 0, wx.ALL | wx.EXPAND, 10)
        subject_label = wx.StaticText(panel, label="主题:")
        send_sizer.Add(subject_label, 0, wx.ALL | wx.LEFT, 10)
        subject_text = wx.TextCtrl(panel)
        send_sizer.Add(subject_text, 0, wx.ALL | wx.EXPAND, 10)
        body_label = wx.StaticText(panel, label="正文:")
        send_sizer.Add(body_label, 0, wx.ALL | wx.LEFT, 10)
        body_text = wx.TextCtrl(panel, style=wx.TE_MULTILINE)
        send_sizer.Add(body_text, 0, wx.ALL | wx.EXPAND, 10)
        send_button = wx.Button(panel, label="发送")
        send_sizer.Add(send_button, 0, wx.ALL | wx.CENTER, 5)
        my_sizer.Add(send_sizer, 0, wx.ALL | wx.EXPAND, 10)
        panel.SetSizer(my_sizer)
app = wx.App(False)
frame = EmailClient(None, "邮件客户端")
frame.Show(True)
app.MainLoop()
